#+title: Uses
#+date: <2022-05-04 00:00>
#+filetags: nocomments

This page is an overview of tools I like to use, and technologies I enjoy.

** Core Technologies
- *Personal Operating System: Ubuntu Linux* \\
  Nine out of ten software engineers agree, it is a miracle that anything works at all. I use Windows daily at work, and know it intimately, and have used macOS in the past. They all work; they all break. But Linux gives me a fighting chance to fix the most annoying problems myself, which is why it is my operating system of choice.
- *Browser: Firefox* \\
  The only truly free browser left. At this point, mostly my choice out of inertia, due to a number of extensions I like.
- *Code Editor: Emacs* \\
  I do most of my work in a text editor. My emacs is my own, it is a custom-built tool for my particular way of working. I code in black-and-white, mostly keyboard-driven. I am under no illusions that this way of working is “more efficient” than other ways, but it sure gives me joy. I love the soothing anachronistic simplicity of this.
- *Image Editor: Darktable* \\
  Really more of a toolkit for building image editing pipelines than a streamlined editing tool. But I am a signal processing scientist after all, and being able to delve into the intricacies of its algorithms and parameters gives me joy. To say nothing of the stellar community around it. But I also use Capture One, depending on mood.
- *Shell: Fish* \\
  Because it does most things correctly out of the box. Strangely, all my previous choices in this list were made for customizability's sake, but my shell is a preconfigured, opinionated one. What can I say, I like it.
** Programming
I like to write my own things instead of relying on ill-fitting panaceas. Professionally: I have implemented my own scripting systems, DNN engines, parsers, file formats, databases, batch processors, audio libraries, language interop. Casually: my own journal, blogging system, photo editing LUTs, photo automations, data analyses. I believe programming to be fundamentally simple, but complicated by APIs and technologies. Less stuff in a program is usually better.

- *Python* \\
  When I need to automate or script, or when I want to explore, Python is a pragmatic choice. Fast enough for most tasks, with libraries for everything imaginable. And where libraries are lacking, I've built my own. I am deeply familiar with the scientific Python ecosystem, and all things audio, as well as tons of automation, file-level, and bit-level programming. I've taught Python for almost a decade as well. It has treated me well.
- *C* \\
  For speed, and portability. I love C for its simplicity, warts and all. There is nothing you can't do in C, but loads of things you shouldn't. My specialty is disecting legacy code bases, and boiling them down to their elegant core. Once everything unnecessary has been taken out, C can truly shine. Just don't try to write Python in C. Please.
- *Lua* \\
  It still blows my mind how tiny Lua is, yet how flexible. Every time I go back into my Lua code bases, I am taken aback by its oddities, yet there is something delightfully composable in its building blocks, that ultimately more than makes up for it. And its source code is a marvel of clean design.
** Blogging
- *Org-Static-Blog* \\
  My own blogging system written in Emacs Lisp, for this very blog. Apparently useful to other people as well. I can't say it's my most elegant invention, but it serves its purpose, and I built it myself.
- *Publii* \\
  A static site generator with a UI, what a radical idea! A joy to use for my private family blog. I wish more software was as neatly simple as this onw.
** Web Services
- *Bookmark Manager: Pinboard* \\
  A simple service for saving URLs that is both my infinite backlog, my watch/read list, and my bookmark manager. And it has an API, too, that I use for fixing youtube links, mostly. It looks bare bones, and it is, but it truly excels at managing bookmarks.
- *Feed Reader: Feedbin* \\
  When GReader went away, I went to Feedbin, and it is completely delightful! I use it to subscribe to RSS, of course, but also Youtube, Reddit, HN, Twitter, and even mailing lists. Well worth the subscription price!
- *Search Engine: Duckduckgo* \\
  There was a time when Google worked for me. But nowadays it seems practically unusable due to SEO spam and ads. Mindblowingly, you can type words into DuckDuckGo, and it will actually search for those words, not “did you mean”, nor “we've als included”. And its bang-searches are plain awesome!
- *Email: Mailbox.org* \\
  A dependable, affordable, privacy-preserving German email provider. I use it for contacts, calendar and email, and it works well.
- *Hosting: Uberspace and Hetzner* \\
  I host my websites on Uberspace, because they're simple and powerful. I host my backups on Hetzner, because their storage boxes are cheap and reliable.
** Hardware
- *Camera: Fujifilm and Ricoh* \\
  A Ricoh GR in my pocket, and a Fuji X-Pro or X-T on a sling, is how I like to roll. These are deeply personal devices, and my creative outlet for capturing the way I see the world. They are wonders of technology, and a haptic joy. I love cameras, have tried many dozens, and these are the ones that struck a nerve.
- *Tablet: Surface 7 Pro* \\
  I love my Surface. It is a terrific media consumption device, but with a real desktop web browser with extensions and ad blockers and everything. And in a pinch, it can even be a real laptop, with a command line and programming tools. I don't have a laptop any more. \\
  I thought I'd miss the iPad and its purpose-built apps. But it turns out I had it the wrong way around. I missed a file system on the iPad, I missed floating windows and true multi tasking, I missed USB accessories. It's the iPad that now feels gimped and restrictive, not the Surface.
- *Ereader: Kobo* \\
  It's such a simple device. A paper-like screen with text on it, to read books on. I love books! But reading from dead trees at night is challenging, and carrying many of them on vacation too cumbersome. My Kobo is a joy to use, and can open standard ePubs. I love it!
- *A Desktop Computer* \\
  I have an actual desktop computer. A fast, “large” thing with a full-sized graphics card and a full-speed CPU. After being sorely disappointed with thermally challenged laptops a few years ago, I fully embraced my desktop. Perhaps that just means I'm old.
- *Smartphone: Android* \\
  Much like with desktop operating systems, I am not thrilled about my choices. But I fractionally prefer Androids hackability and price point. I wish my phone got software updates for longer than it does, and I wish Google's software was less intrusive, though.
