#+title: A Digital Thank You
#+date: <2014-12-20 0:00>

This is the time of the year when we reflect on our lives, and be thankful. We write Christmas cards to people we like, and celebrate with our loved ones. At my job, I am sitting in front of a screen all day, and I interacted not only with people, but also their software. So this is a column where I want to thank people I don't know for their delightful software:

** [[http://orgmode.org/][Org Mode]]
Thank you, Carsten Dominik, Bastien Guerry, and [[http://orgmode.org/org.html#History-and-Acknowledgments][everyone else]], for this amazing piece of software! I have used Org mode for my [[https://github.com/bastibe/org-journal][research journal]], [[http://bastibe.de/2013-11-13-blogging-with-emacs.html][this blog]], [[http://bastibe.de/2014-11-19-writing-a-thesis-in-org-mode.html][writing my thesis]], general note-taking, and all-around planning tool. Thank you for making my life so much easier to manage!

** [[https://github.com/mgeier][Matthias Geier]]
Thank you, Matthias, for your many contributions to [[https://github.com/bastibe/PySoundFile][PySoundFile]] and [[https://github.com/bastibe/PySoundCard][PySoundCard]], and our many enlightening discussions. You have brought these two projects far further than I would have ever gone, and I learned a lot in the process! Also, a quick thank you to Github, which made our collaboration effortless and enjoyable.

** [[http://fishshell.com/][fish]]
Thank you, [[http://ridiculousfish.com/][Ridiculous Fish]], for bringing sane scripting, glorious VGA color, and general awesomeness to the command line! Finally, a shell that does not drown you in messy configuration, crazy syntax, and archaic conventions. Finally, a shell with beautiful documentation, and sane defaults! Thanks for all the fish!

** [[http://www.getsync.com/][BitTorrent Sync]]
Dropbox is awesome, no doubt, but it still feels awkward to upload all my documents to a faceless corporation. Synchronizing data between computers is still hard--or rather, used to be hard. Because this year I discovered btsync. I now have a real off-site backup and file synchronization system fully under my own control, and it took all of ten minutes to set up. Thank you!

** [[http://x-plane.com][X-Plane]]
This year, I got back into an old hobby of mine: Flight Simulation. In particular, this year I re-discovered X-Plane, and the marvelous and free sceneries by [[http://simheaven.org/][SimHeaven]] and [[http://www.alpilotx.net/][Andras Fabian]]. Sadly, there doesn't seem to be any pilot school around where I can complete my real-world pilot's license, so flight simulation will have to do. But with this simulator, I am enjoying flight simulation more than ever!
