#+title: Books of 2014
#+date: <2014-12-30 0:00>
#+tags: books

** [[http://www.amazon.de/Ancillary-Justice-Imperial-Radch-English-ebook/dp/B00BU1DG1S/ref=sr_1_1?s=books-intl-de&ie=UTF8&qid=1419948379&sr=1-1&keywords=ancillary+justice][Ancillary Justice]] / [[http://www.amazon.de/Ancillary-Sword-Imperial-Radch-English-ebook/dp/B00IA2E5VA/ref=sr_1_2?s=books-intl-de&ie=UTF8&qid=1419948379&sr=1-2&keywords=ancillary+justice][Ancillary Sword]], by Ann Leckie
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/6/6a/Ann_Leckie_-_Ancillary_Justice.jpeg
I have been reading a lot of science fiction in the last few years. These books are part one and two of the best space opera I have ever read. The story is written from the perspective of an AI, sometimes inhabiting a lot of bodies, sometimes only one. Interestingly, this makes for a very introspective viewpoint, where politics and actions are expressed as consequences of nuanced human behavior and astute observation, as opposed to arbitrary human decisions. This perspective is extremely compelling, and makes for an extremely /human/ story in a world that is a clever amalgamation of ancient Roman society and post-modern egalitarianism. There is no book I look forward to more fiercely than the conclusion of this series.

** [[https://en.wikipedia.org/wiki/Scott_Pilgrim][Scott Pilgrim]], by Bryan Lee O'Malley
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/3/39/ScottPilgrim.jpg
Scott Pilgrim is a twenty-something in the nineties. Scott Pilgrim doesn't have a job, and likes to play video games. Scott Pilgrim is fighting epic Anime battles against his girlfriends' exes. Scott Pilgrim is everyone, living in the real world. Scott Pilgrim is awesome, especially the new color-versions. The last part of the series will be released next year, and I really can't wait! (There's also a movie that is supposedly very good, but I won't watch it until I read all the comic books).

#+begin_html
<br><br>
#+end_html

** [[http://www.amazon.de/Doomsday-Book-Connie-Willis/dp/0553562738/ref=sr_1_sc_2?ie=UTF8&qid=1419948450&sr=8-2-spell&keywords=doomsday+boo][Doomsday Book]], by Connie Willis
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/1/19/DoomsdayBook%281stEd%29.jpg
This is about time travel from near-future Britain to the fifteenth century. But then, an epidemic breaks loose: Britain is in quarantine and civil order starts breaking. At the same time in the fifteenth century, the plague hits. Disease, and the people trying to deal with it, is a human tragedy beyond belief. Connie Willis manages to write about these things with empathy, and astounding humane love and humor. This story moved me more deeply than I care to acknowledge.

#+begin_html
<br><br><br>
#+end_html
