#+title: Decisions in Pillars of Eternity
#+date: <2015-04-12 0:00>
#+tags: games

Early on in [[https://en.wikipedia.org/wiki/Pillars_of_Eternity][Pillars of Eternity]], you are tasked to kill one of two characters: Either you kill King Rethoric, who executed many innocent people, or you kill Rolsc, the leader of the rebellion. This is an interesting moral choice, but it is also profoundly sad that the game presents killing either of them as the only resolution to this conflict.

It got me thinking. In the real world, I would not consider killing to be an option, ever. But in the game, you have to play by the game's rules. And furthermore, you can't just walk away and have the two characters duke it out amongst themselves: The whole game is built around the player, and without the player's interaction, the game world doesn't evolve.

Thus, this conflict won't resolve itself, and the player is forced to kill. I wish there were a diplomatic option, or a way of fixing the underlying problem so the two characters are not at odds any more. I fear how these choices in video games might influence our perceptions of everyday choices, and crave for video games that offer interesting choices that do not revolve around murder.

From what I hear, Planescape Torment did offer such choices. As did many of [[https://en.wikipedia.org/wiki/Gone_Home][my]] [[https://en.wikipedia.org/wiki/The_Stanley_Parable][favorite]] [[https://en.wikipedia.org/wiki/X-Plane_%2528simulator%2529][games]] [[https://en.wikipedia.org/wiki/Civilization_V][of]] [[https://en.wikipedia.org/wiki/The_Wolf_Among_Us][all]] [[https://en.wikipedia.org/wiki/The_Witcher_%2528video_game%2529][times]].
