#+title: MATLAB Syntax
#+date: <2016-09-07 00:00>

In a [[https://github.com/bastibe/MatlabCodeAnalyzer][recent project]], I tried to parse MATLAB code. During this trying exercise, I stumbled upon a few... /unique/ design decisions of the MATLAB language:

** Use of apostrophes (~'~)
Apostrophes can mean one of two things: If applied as a unary postfix operator, it means /transpose/. If used as a unary prefix operator, it marks the start of a string. While not a big problem for human readers, this makes code surprisingly hard to parse. The interesting bit about this, though, is the fact that there would have been a much easier way to do this: Why not use double quotation marks for strings, and apostrophes for transpose? The double quotation mark is /never/ used in MATLAB, so this would have been a very easy choice.

** Use of parens (~()~)
If Parens follow a variable name, they can mean one of two things: If the variable is a function, the parens denote a /function call/. If the variable is anything else, this is an indexing operation. This can actually be very confusing to readers, since it makes it entirely unclear what kind of operation ~foo(5)~ will execute without knowledge about ~foo~ (which might not be available until runtime). Again, this could have been easily solved by using brackets (~[]~) for indexing, and parens (~()~) for function calls.

** Use of braces (~{}~) and cell arrays
Cell arrays are multi-dimensional, ordered, heterogeneous collections of things. But in contrast to every other collection (structs, objects, maps, tables, matrices), they are not indexed using parens, but /braces/. Why? I don't know. In fact, you /can/ index cell arrays using parens, but this only yields a new cell array with only one value. Why would this ever be useful? I have no explanation. This constantly leads to errors, and for the life of me I can not think of a reason for this behavior.

** Use of line breaks
In MATLAB, your line can end on one of three characters: A newline character, a semicolon (~;~), and a comma (,). As we all know, the semicolon suppresses program output, while the newline character does not. The comma ends the logical line, but does not suppress program output. This is a relatively little-known feature, so I thought it would be useful to share it. Except, the meaning of ~;~ and , changes in literals (like ~[1, 2; 3, 4]~ or ~{'a', 'b'; 3, 4}~). Here, commas separate values on the same row and are optional, and semicolons end the current row. Interestingly, literals also change the meaning of the newline character: Inside a literal, a newline acts just like a semicolon, overrides a preceding comma, and you don't have to use ellipsis (~...~) for line continuations.

** Syntax rules for commands
Commands are function calls without the parenthesis, like ~help disp~, which is syntactically equivalent to ~help('disp')~. You see, if you just specify a function name (can't be a compound expression or a function handle), and don't use parenthesis, all following words will be interpreted as strings, and passed to the function. This is actually kind of a neat feature. However, how do you differentiate between ~variable_name + 5~ and ~help + 5~? The answer is: Commands are actually a bit more complex. A command starts with a function name, followed by a space, which is not followed by an operator /and a space/. Thus, ~help +5 + 4~ is a command, while ~help + 5 + 4~ is an addition. Tricky!

** The more-than-one-value value
If you want to save more than one value in a variable, you can use a collection (structs, matrices, maps, tables, cell arrays). In addition though, MATLAB knows another way of handling more than one values at once: The thing you get when you index a cell array with ~{:}~ or assign a function call with more than one result. In that case, you get something that is assignable to several variables, but that is not itself a collection. Just another quirk of MATLAB's indexing logic. However, you can capture these values into matrices or cell arrays using brackets or braces, like this: ~{x{:}}~ or ~[x{:}]~. Note that this also works in assignments in a confusing way: ~[z{:}] = x{:}~ (if both x and z have the same length). Incidentally, this is often a neat way of converting between different kinds of collections (but utterly unreadable, because type information is hopelessly lost).
