#+title: Books of 2015
#+date: <2016-01-06 00:00>
#+tags: books

** [[https://www.goodreads.com/book/show/8706185-among-others][Among Others]], by Jo Walton
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/d/d1/Among_Others_%28Jo_Walton_novel%29.jpg
I don't usually enjoy fantasy novels and their romantic escapism. I much prefer fascinating sci-fi thought experiments. But this book won all the most important awards, so I gave it a shot. What if random chance could be bent a little with creativity, the power of believing in something, and some mysticism? You end up with a world that is richer, more meaningful, and altogether more alive, if you just cared to observe and to appreciate it's beauty. Reading this book left me enchanted and more observant long after I put it down. What a wonderful book!

** [[https://www.goodreads.com/book/show/7073.A_Son_of_the_Circus][A Son of the Circus]], by John Irving
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/e/e7/ASonOfTheCircus.JPG
This is one of those books that was on my to-read list for months. It starts out as quirky and likeable as you would expect from John Irving. This time, we follow the tale of a Canadian/Indian doctor throughout his life, and his summer vacation in India. But this would not be John Irving if there weren't plenty of colourful characters, astute observations of human strangeness, and a meticulously crafted story. There is no scene in this book that does not serve a purpose, and so many moving parts my mind just boggles at the construction of it all. Yet at the same time, I was regularly laughing out loud. I loved every minute of this!

** [[https://www.goodreads.com/book/show/6597651-the-windup-girl][The Windup Girl]], by Paolo Bacigalupi
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/1/1f/Wind_up.jpg
The whole world changed in the near future, when gasoline is a rare luxury, sea levels have risen and swallowed all the coastal cities, and man-made scourges have devastated most crops. And now it's not just humans that populate our urbanized world, but so too are our inventions, artificial humans called "windups" for their stutter-stop movements. But at the core, both humans and windups struggle for the same security, prosperity as ever. Such an inventive world, so much vivid creativity, social commentary, in this human struggle to not destroy ourselves.

** [[https://www.goodreads.com/book/show/629.Zen_and_the_Art_of_Motorcycle_Maintenance][Zen and the art of motorcycle maintenance]], by Robert Pirsig
#+ATTR_HTML: :style float:left;margin:5px; :width 150px
https://upload.wikimedia.org/wikipedia/en/8/85/Zen_motorcycle.jpg
This is about equal parts a motorcycle journey of a father and his son across the US, and a dive into another man's discoveries of philosophy. To be honest, I liked this book more for it's character descriptions and travelling adventures than it's philosophy. I am really conflicted about putting this book on this list at all, but I kept thinking about this long after I finished reading it, so I guess this had a bigger influence on me than I realized.

** Nexus/Crux/Apex, Rad/Blue/Green Mars, The Martian, The Three-Body Problem
What happens when you take today's world, and add nanotech brain upgrades (Nexus/Crux/Apex), or strand a lone scientist on Mars (The Martian), or send a large number of people to found a new colony on Mars (Red/Blue/Green Mars), or suddenly make contact with Aliens (The Three-Body Problem)? This what-if is what Science Fiction does best: Take this little what-if, and spin a gripping yarn from that. These books inspired me, made me think, were incredibly thrilling, but they did not have a lasting impact. Still well worth a read if you like Science Fiction, though.
