#+title: P⋅O⋅L⋅L⋅E⋅N and Walk 'em ups
#+date: <2016-06-26 00:00>

I like boring games. I like games that give me time to think. Like [[http://x-plane.org/][flight]] [[http://www.prepar3d.com/][simulators]], [[http://eurotrucksimulator2.com/][truck]] [[http://www.americantrucksimulator.com/][simulators]], [[https://en.wikipedia.org/wiki/Civilization_V][history simulators]], and (don't call them walking simulators) [[https://en.wikipedia.org/wiki/The_Stanley_Parable][walk]] '[[http://gonehome.game/][em]] [[http://www.firewatchgame.com/][ups]]. And this weekend, this year's Steam Summer Sale started, and thus it was time to get some gaming done!

First, I played [[https://en.wikipedia.org/wiki/Everybody%27s_Gone_to_the_Rapture][Everybody's Gone to the Rapture]], a walk 'em up that got good reviews, and was especially praised for it's story. And it dutifully enraptured me, with its British landscapes, and personal story lines. But somehow it didn't quite connect. Maybe I'm not [[http://www.gamesradar.com/how-enjoy-everybodys-gone-rapture-real-englishman-explains/][British]] enough, and I certainly didn't get all of the story. Still, this is well worth picking up, and visiting a digital Shropshire after just having visited the real one earlier this year was a real treat!

Second, I played P⋅O⋅L⋅L⋅E⋅N. It did not start well: The download took ages, I had to unplug all that fancy flight simulation gear to get it to recognize my controller, and performance was rather lackluster. Oh, and reviews were rather mediocre, too. (Also, here's a free tip for you if you games developers: putting fancy Unicode characters into your game title does not improve SEO).

But, I entirely fell in love with P⋅O⋅L⋅L⋅E⋅N! You arrive on [[https://en.wikipedia.org/wiki/Titan_(moon)][Titan]] in your dinky near-future space capsule, take a short walk on the surface of the moon, and then explore the local space station. Of course, something went wrong, and the space station is deserted. Oh, and there is something about space bees.

What really worked for me here was the environmental story telling. This is a space station much in the tradition of [[https://typesetinthefuture.com/2014/01/31/2001-a-space-odyssey/][2001: A Space Odyssey]] and [[https://typesetinthefuture.com/2014/12/01/alien/][Alien]]. It's that perfect utilitarian and inhumanely sterile work place that human corporation always strive for, and human employees always mess up. The stark industrial bleakness of these [[http://scificorridorarchive.com/][space corridors]] is the perfect backdrop to make those little human irregularities really stand out.

There is no conflict, only light puzzles, and the story is developed only through voice diaries and environmental clutter. But in contrast to Rapture, it all makes sense. The futurist setting, the deep humanity of the people dealing with it. The creepiness of machines without operators. The struggle of the scientists and engineers against the forces of nature and greedy corporations. The nods —nay— genuflections to everything that has ever been great in Scifi. Even that Kubrick ending. I loved every inch of this! ★★★★★
