#+title: Dropbox deleted my pictures and Time Machine didn't backup
#+date: <2017-12-28 00:00>

Dropbox deleted some of my favorite pictures. Have you looked at all your old pictures lately and checked if they are still there? I have, and they were not. Of course Dropbox denies that it is their fault, but no other program routinely accessed my pictures. [[https://www.dropboxforum.com/t5/Missing-files-and-folders/Randomly-deleted-files-and-folders/td-p/203952][I am not alone with this problem]]. It must have happened some time between the summer of 2015, when I put my pictures on Dropbox, and the summer of 2016, when Time Machine last corrupted its backups and had to start over, thereby deleting my last chance of recovering my pictures. The pictures are gone for good.

So, what have I learned? Dropbox loses your data, and Time Machine can't restore it. These programs are obviously no good for backups. Let me repeat this: *Dropbox and Time Machine are not a backup!* A true backup needs to be reliable, keep an infinite history, and /never/, /never/, /never/ accidentally delete files.

From now on, I will use [[http://rsnapshot.org/][rsnapshot]] for backups. [[https://rayed.com/wordpress/?p=1693][Here]]'s a tutorial on how to set it up on a Mac. I have used rsnapshot for years at work, and it has never let me down. For syncronizing things between computers, I now use [[https://syncthing.net/][syncthing]]. both of these programs are not as user-friendly as Dropbox or Time Machine, but that is a small price to pay for a working backup.

A few years ago, I had high hopes that [[http://bastibe.de/2009-03-14-get-a-mac.html][Apple]] and [[http://bastibe.de/2009-03-28-synchronisieren-von-google.html][Dropbox]] and Google and Amazon would lead us to a bright future of computers that "just work", and could solve our daily chores ever more conveniently and reliably. But I was proven wrong. [[http://bastibe.de/2012-07-09-apple-is-failing-me.html][So]]. [[http://bastibe.de/2012-11-01-apple-tv.html][Many]]. [[http://bastibe.de/2015-10-16-finder-woes.html][Times]]. It seems that for-profit software inevitably becomes less dependable as it adds ever more features to attract ever new users. In contrast, free software can focus on [[http://bastibe.de/2017-10-24-the-long-game.html][incremental improvements and steadily increasing reliability]].
