#+title: Scheduling Future TODOs in org-journal
#+date: <2018-04-02 11:38>
#+filetags: org-journal org-mode

I keep a simple journal in [[https://github.com/bastibe/org-journal][org-journal]]: One text file per day, in [[https://orgmode.org/][org-mode]]. But over the years, org-journal has grown somewhat beyond this simple use case. [[https://github.com/bastibe/org-journal/releases/tag/1.7.1][About three years ago]], a gentleman named [[https://github.com/vkazanov][Vladimir Kazanov]] implemented a very fast text search. Thus, my journal became an information archive. [[https://github.com/bastibe/org-journal/releases/tag/1.11.0][About two years ago]], org-journal learned to carry over TODO items to the current day if you hadn't completed them on the previous day. So it to become a to-do list. And [[https://github.com/bastibe/org-journal/releases/tag/1.13.1][today]], org-journal gained the ability to work with future journal entries, thus becoming a calendar.

Despite all of these features however, org-journal remains one org file per day, with fancy functions to do fancy things if you want them—or ignore them, if the journal is all you need.

Back to scheduling: This work was prompted by [[https://zngguvnf.org/][my colleague]], who organizes everything in org-mode, but is not a user of org-journal. He even eschews the use of a traditional calendar, and instead uses a few org files and the magic of org-agenda to give him a nice overview like this for the coming week[1]:

#+begin_html
<pre>
<span style="color: #111111; font-weight: bold;">Week-agenda (W14):</span>
<span style="color: #111111; font-weight: bold; font-style: italic;">Monday     2 April 2018 W14</span>
<span style="color: #111111;">  2018-04-02: Easter Monday </span>
<span style="color: #111111; font-weight: bold;">Tuesday    3 April 2018</span>
<span style="color: #111111; font-weight: bold;">Wednesday  4 April 2018</span>
<span style="color: #111111; font-weight: bold;">Thursday   5 April 2018</span>
<span style="color: #111111;">  2018-04-05: Scheduled:  Give Lecture 4 on Applied Programming</span>             <span style="color: #111111;"><span style="font-weight: bold;">:BB:</span></span>
<span style="color: #111111; font-weight: bold;">Friday     6 April 2018</span>
<span style="color: #111111;">  2018-04-06: Scheduled:  Release of new Eels record</span>
<span style="color: #111111; font-weight: bold;">Saturday   7 April 2018</span>
<span style="color: #111111; font-weight: bold;">Sunday     8 April 2018</span>
<span style="color: #111111;">  2018-04-08: Scheduled:  </span><span style="color: #111111;">TODO</span><span style="color: #111111;"> Celebrate Sunday</span>
</pre>
#+end_html

And lo and behold, this now works in org-journal as well! Just create a new journal entry in the future, either by pressing ~i j~ in ~M-x calendar~ or by calling ~org-journal-new-scheduled-entry~, and org-journal will create an entry with a ~SCHEDULED~ property of the appropriate date (prefix to suppress ~TODO~). When the current day reaches that entry, it will incorporate it into the daily journal.

Future journal entries are highlighted in ~M-x calendar~, and you can get an overview of them with ~org-journal-schedule-view~, or, if you enable ~org-journal-enable-agenda-integration~, through the ordinary ~org-agenda~, as shown above. The agenda integration does not include past journal entries in the agenda, since agenda searches tend to become very slow if they have to traverse the hundreds of files in my journal.

[1]: This is of course not /his/ calendar, but mine.
