#+title: Appreciation for Open Source and Commercial Software
#+date: <2018-10-14 10:20>
#+filetags: open-source thank-you

I recently released my first-ever piece of commercial software, a [[https://missiongenerator.eu/][plugin]] for the [[https://www.x-plane.com/][X-Plane]] flight simulator. I wrote this primarily to scratch my own itch, but thought other users might like it, too, so I put it up on [[https://store.x-plane.org/Mission-Generator_p_877.html][the store]]. What struck me however, were the stark difference between the kinds of responses I got to this, as compared to my open source projects: They were astonishingly, resoundingly, /positive/!

You see, I have a bunch of open source projects, with a few thousand downloads per month, and a dozen or so issues on Github per week. Most of my interactions with my users are utilitarian, and efficient. Someone reports a bug or asks for help, I ask for clarification or a pull request, we iterate a few times until the issue is resolved. The process is mechanical and the tone of our conversation is equally unemotional. This is as it should be.

After having released my flight simulator plugin, however, people /thanked me/! They /congratulated me/! They extolled about the greatness of what I had built! And they did this despite the fact that the initial release had quite a few major bugs, and even flat-out did not work for some people. Yet even people who couldn't get it to work were /grateful/ for my help in resolving their issue!

This /blew my mind/, in comparison with the drab "I found a bug", "Could you implement…" I was used to from my open source work. There, the feedback I got was mostly neutral (bug reports, feature requests), and sometimes even negative ("You broke something!"). So I release my software /for free/, as a gift, and get average-negative feedback. My commercial work, in contrast, /costs money/, and yet the feedback I get is resoundingly positive! I can not overstate how motivating it is to get praise, and love, from my users.

I think this is a huge problem for our Open Source community. I had my run-ins with burnout, when all the pull requests came to be too much, and I started dreading the little notification icon on Github. And I think the negativity inherent in bug reports and feature requests has a huge part to do with this. In the future, I will try to add more praise to my bug reports from now on, just to put things into perspective.

But I think we should go further than that. We should create tools for praising stuff, beyond the impersonal Stars on Github. We should be able to write reviews on Github, and recommendations, and blog posts about cool libraries we find.

I recently got my first github issue that was [[https://github.com/bastibe/org-static-blog/issues/12][just a thank-you note]]. I loved it! We need more positivity like that.
