#+title: Learning about Photography: Sunstars
#+date: <2019-03-13 20:17>
#+filetags: photography

Normally, when you take a picture of something too bright, you get /bloom/: An all-consuming brightness that plunges everything around it into pure whiteness. Ugly.

But if the light source is /reeeally/ tiny, and your aperture is /teeeensy/ as well, you get something else: sunstars

https://bastibe.de/static/2019-03/sunstar.jpg

This particular sunstar has fourteen corners, and therefore comes from a seven-bladed aperture (in my Fuji XC 16-50). It happens because tiny apertures are not perfectly circular any longer, but instead, in my case, septagonal, and therefore bloom more in some directions than in others. The effect is kind of beautiful.

In this picture, the sun was just barely peeking into the edge between the tree and the building, and my aperture was set to its smallest setting, f22. I actually wanted to capture the raindrops on the branches, which I largely failed at. In the end, the picture didn't turn out very pretty, but at least I got some fine sunstars!
