#+title: On camera sensor sizes
#+date: <2019-03-25 20:20>
#+filetags: photography

A common internet wisdom about photography is that bigger camera sensors capture more light. So if you want to work in low light, you need a full frame camera, and a bigger sensor always produces better image quality. I have struggled with this a lot. It just doesn't make sense: Lenses can focus light on any surface, so /why should the surface size matter/?

The answer turns out to be... disappointing. Big-sensor cameras allow for larger (practical) apertures, and lower base ISO. But less noise for the same picture is simply impossible with the same sensor technology. Because that's not how physics works. Let me explain.

/At this point, I would launch into a long-winded explanation on [[https://photographylife.com/equivalence-also-includes-aperture-and-iso][equivalence]], and reached a slightly misguided conclusion. So here's a better one:/

It is possible to build /equivalent/ lenses for differently sized sensors, which capture the same amount of light, with the same depth of field, and the same field of view, but simply project this light on a differently sized sensor. Or you can use a "speed booster", which adapts a "bigger" lens to a "smaller" sensor. Both of these will give you identical images, and identical amounts of noise (if the same sensor technology is used).

As an example, a micro four thirds 23mm f/1.4 lens produces identical images to an APS-C 35mm f/2 lens or a full frame 50mm f/2.8 lens. You might notice that $\frac{23}{1.4} = \frac{35}{2} = \frac{50}{2.8}$, which means each of these lenses will have the same physical aperture size, and therefore admit the same amount of light. And be the same size and weight. Since the smaller sensor collects the same light on a smaller sensor (smaller f-number), the image will be brighter, and will need to use a lower ISO for the same exposure. And since lower ISO produces less noise, the "one stop advantage" of bigger sensors is bunk, /if equivalent lenses are used/.

The one remaining difference between sensor sizes is that bigger photosites carry more charge, which means more dynamic range at base ISO on a bigger sensor. This is only a factor if you indeed shoot at base ISO.

/But/, that's not the interesting part. Because camera manufacturers cleverly designed their product lines such that small-sensor cameras are built smaller, and get smaller lenses, while large-sensor cameras are bigger, and get bigger lenses. Thus, if you want to get access to the most fancy glass, you will have to use a bigger, more expensive camera body as well. And that's not pure marketing, either, as there really isn't much value in having a tiny camera body if you pair it with a lens three times its size and weight (and vice versa).

So in the end, it comes down to a compromize: If you want/need the best glass, it will necessarily be heavy, and will need to be paired with a bigger camera body for practicality alone. And once you have that, you might as well use a bigger sensor as well. On the flip side, if you want small and light, you will necessarily have to sacrifice big apertures, and a smaller sensor and body will be a better match.
