#+title: On camera sensor sizes
#+date: <2019-03-25 20:20>
#+filetags: photography

A common internet wisdom about photography is that bigger camera sensors capture more light. So if you want to work in low light, you need a full frame camera, and a bigger sensor is always better. I have struggled with this a lot, though, because it doesn't make sense. Lenses can focus light on any surface, so /why should the surface size matter/?

The answer turned out to be... disappointing. Bigger sensors allow for larger (practical) apertures, and lower base ISO. But less noise for the same picture, is simply impossible with the same sensor technology. Because that's not how physics works. Let me explain.

Let's talk about three sensor sizes, full frame (FF), APS-C, and micro four thirds (MFT). For the sake of discussion, let's assume that these sensor sizes are always a factor of $\sqrt{2}$ of each other, which is close enough to the truth. So FF is twice the area of APS-C, which is twice the area of MFT. Let's also assume that our hypothetical cameras at these sizes use sensors with the same resolution, and using the same technology. With that out of the way, what does it mean to use a smaller sensor?

If you shrink the sensor area by a factor of two, every pixels gets equally smaller, and receives less light (on the same lens). To fix this, and account for the different field of view due to cropping, we zoom out, dividing the focal length by $\sqrt{2}$. So now a FF 35mm f4 lens will get the same field of view and brightness as an APS-C 23mm f4 lens, or a 17mm MFT f4 lens, all at the same ISO number. The only difference being, that due to the smaller sensor, MFT will be twice as noisy as APS-C, which is twice as noisy as FF. This seems like a clear win for FF, right?

As an aside, isn't it cool that we actually get the same brightness, as long as ISO and f-numbers are kept the same? That's what they are designed to say: Equal ISO and f-number means equal brightness! (But not equal noise, or, as we will see, equal depth of field).

Because here's the catch: Even though the f-number is the same, the physical size of the aperture is bigger on the bigger sensor! This makes sense, because to get the same brightess on a bigger sensor area, you need more light. And to get more light, you need a bigger aperture. This also means that the depth of field on the FF sensor is twice as big as on the APS-C sensor, which is twice as big as the MFT sensor.

So let's account for that, too, and give each camera a lens with the same physical aperture size as well as field of view, and stop down ISO to account for the increase in brightness: FF 35mm f4 ISO 1600 then becomes APS-C 23mm f2.8 ISO 800 and MFT 17mm f2 ISO 400. These combinations now actually have the same field of view, same brightness, same depth of field, and, you guessed it, same noise. If you account for field of view, there is no advantage to FF whatsoever. You can get the very same picture on a big sensor as on a small sensor, the only difference being how much you are willing to carry and pay for it.

OK, that's not quite true: You can get FF lenses at f1 (equivalent to f0.7 on APS-C or f0.5 on MFT), which are just not available on smaller sensors. But have you used such lenses? At this point, the area in focus is literally razor-thin, and focusing becomes terrifyingly difficult. You might also notice that wider-aperture lenses are generally bigger. They have to be, to capture more light. By the same token, an f1.4 APS-C lens will be the same size as an f2 FF lens (because it is in fact mostly identical). And FF offers smaller base ISOs. If you need the minimum amount of noise, ISO 100 on FF would be equivalent to ISO 25 on MFT, which you just can't get, there.

TL;DR: Bigger sensors afford bigger apertures, with all their associated downsides. But they do not magically reduce image noise (everything else being equal). Also, cameras are surprisingly complex beasts.
