#+title: Books of 2018
#+date: <2019-01-06 10:54>
#+filetags: books

There is no other media more immersive to me than reading. When I read, I dive deep into another world, and seize to perceive the reality around me. It is my escape from the everyday stresses of living in the modern world. Reading is truly sacred to me. So here are my favorite pieces of writing of 2018:

* [[https://www.goodreads.com/book/show/9530.Shadow_Divers][Shadow Divers]]
#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2019-01/shadow-divers-cover.jpg

This is a book about deep wreck diving. I am not interested in wrecks, or diving. Nevertheless, no book gripped me as hard last year as Shadow Divers. At first, I was a bit thrown off by the writing style, and thought it dramatized things too much. But I just couldn't put this book down. There were times when I surfaced from reading with a distinct feeling of having been there, of having touched that menacing shipwreck at the bottom of the ocean.

By the end of it, I was entirely engrossed in the story and its characters and the history of the mystery wreck. And then, in the epilogue, I learned that what I had thought embellished at first was actually meticulously researched and not overdramatic at all.

And best of all, my favorite podcast, [[http://omegataupodcast.net][Omega Tau]] had [[http://omegataupodcast.net/33-deep-wreck-diving/][an interview]] with the main protagonist of the book, which is just fascinating!

* [[https://www.goodreads.com/book/show/34757960-the-shortest-history-of-germany][The Shortest History of Germany]]
#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2019-01/german-history-cover.jpg

This book is a strange choice to put on my list of books, because I didn't like it too much. I found it offputting which parts of history the author emphasized, and which parts he skipped. Apparently, the two world wars did not bear mentioning. The book paints a strangely specific west-vs-east map of Germany, which is not without merit, but surely not the whole story. And worst of all, I really didn't care for the writing style at all.

But when I look back on 2018, this book has stuck with me. Never mind its shortcomings, it has given me a map of Germany's history that I can fit other pieces of knowledge into. And that makes it valuable to me.

* [[https://uncannymagazine.com/article/and-then-there-were-n-one/][And then there were (N-One)]]
#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2019-01/n-1-cover.jpg

I love short stories. And this one is just brilliant. It is by Sarah Pinsker, about Sarah Pinsker, and all Sarah Pinskers from neighboring parallel universes. Every character in this book is a Sarah Pinsker. And all of them agree, Sarah is no murderer. Yet, one of them has been found murdered.

I won't spoil more of it, just head over to the [[https://uncannymagazine.com/article/and-then-there-were-n-one/][Uncanny Magazine]] and read it for yourself!

* Graphic Novels
For years now, I have struggled to find graphic novels that speak to me. I usually find the drawing style off-putting, and would have preferred a more fleshed out novel instead of a shallow graphic novel. But this year, I found two brilliant graphic novels that I loved dearly:

- [[https://www.goodreads.com/book/show/15195.The_Complete_Maus][Maus]]
#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2019-01/maus-cover.jpg

The half-auto-biographical narrative of a survivor of one the Nazi concentration camps. The novel juxtaposes the author's struggle to interview his father about his past, and thereby shows both the cruelty of the father's experience, and the man that this experience created. Both of these perspectives add weight to the unspeakable nastiness of the Holocaust.

But beyond that, it is also a story of humanity, struggle, and the small moments of joy amidst all the terror. Truly a masterpiece of a book.

- [[https://www.goodreads.com/book/show/19351043-nimona][Nimona]]
#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2019-01/nimona-cover.jpg

In sharp contrast to the previous book, Nimona is just plain fun! Nimona is a teenage girl, and a shark, and the sidekick of Balister Blackheart, the biggest name in Supervillainy. And if you haven't guessed it from this description, it is wacky, and funny, and uplifting, and just... fun!

You can read the first three chapters [[http://gingerhaze.com/nimona][online]], and then you'll want to read the rest, too. It's just too much fun!
