#+title: The Value Proposition of Open Source Software
#+date: <2020-03-27 08:17>
#+filetags: programming open-source

To [[https://en.wikipedia.org/wiki/Open-source_software][quote Wikipedia]]:

#+begin_quote
Open Source Open-source software (OSS) is a type of computer software in which source code is released under a license in which the copyright holder grants users the rights to study, change, and distribute the software to anyone and for any purpose.
#+end_quote

In practice, this generally means software developed by hobbyists in their free time, as opposed to professionals at a company.

But why should such software be preferable to commercial products? I shall ignore price, for the moment. While open source software generally does not cost money, I have no qualms about paying money for software, and can easily afford to, as well. So if it's not price, what then?

Richard Stallman makes an argument that it's [[https://www.gnu.org/philosophy/open-source-misses-the-point.html][all about Freedom]]. But I have a suspicion that he really wants the /code/ to be free, not its users[fn::See [[https://louigiverona.com/?page=projects&s=writings&t=philosophy&a=philosophy_freedoms][this link]] for an exhaustive discussion of that topic. It's an amazing article!]. He argues that "free" licenses make the program's source code available to users. Presumably, to read it and change it. However, I don't do that, generally. And neither do I redistribute software, which is another "freedom" granted by Stallman-style free software. Also, [[https://discourse.ardour.org/t/is-open-source-a-diversion-from-what-users-really-want/102665][you don't need access to the source code to change a software]]. But I still prefer Open Source Software to commercial software, in most cases.

And the reason is, that in my experience, Open Source Software is generally better software. And I believe the reason for this is incentives:

Open Source Software is generally created to scratch an itch. One single developer was sufficiently disgruntled to throw all caution into the wind, and solve the problem him/herself. Which means that at least one person was dissatisfied with the commercial offerings at the time.

And there are plenty of reasons to be dissatisfied with commercial software. Commercial software needs to make money. And to justify recurring sales, it must keep adding features, often beyond the usefulness to users. Thus, big changes and new features are incentivized, while continued refinement and bug fixing are merely cost centers.

Contrast this with Open Source Software, which is quite content to simply /work/. No new features need to be added if the software is complete as it is, and no new effort needs to be invested if there aren't any bugs remaining. Such software is a joy to use.

In the commercial world, such software is not /stable/, but /stagnant/. A sign of death, not maturity. And when commercial software dies, it is buried, never to be used again. And all the work its users have created with it over the years, [[https://en.wikipedia.org/wiki/Aperture_(software)][becomes inaccessible and obsolete with it]]. In the same way, today's online-only subscription-based software distributions are essentially protection rackets that require a monthly ransom just to keep access to your existing work. The moment you stop paying, all your previous work becomes inaccessible. Such moves are indeed Stallman-worthy invasions of freedom that are unacceptable to me[fn::Except for video games, which I only consume once, and which result in experiences, not artifacts. Strange, how this distinction is surprisingly hard to justify.].

Of course, Open Source Software allows users to contribute to the product. But In my own projects, I have found this to vary greatly between cultures. Some communities seem to be naturally tinker-friendly, such as [[https://github.com/bastibe/org-journal][Emacs]] or [[https://github.com/darktable-org/darktable][Darktable]]. Others, such as [[https://github.com/bastibe/SoundCard][Python's]] or [[https://github.com/bastibe/Violinplot-Matlab][Matlab's]], are strangely reluctant to help one another, with more users creating bug reports than contributors creating pull requests.

Funny enough, price does not enter this equation. Because what you need to use Open Source Software is often not money, but time. And only rich people have that. If you're poor, and paying for software is a problem, you're far more likely to pirate "professional" software with a known value proposition, than to spend time on an unknown quantity. Open Source Software is a [[https://discuss.pixls.us/t/darktable-user-survey/16824][toy for the rich]], and paradoxically unattractive to people in need[fn::User-facing software, that is. Linux web servers are for everyone].

So in summary, I have generally found Open Source Software to be /better/ than commercial software in most circumstances. Perhaps as a next step, we should try to figure out how to get payed for creating it, and how to keep monetary incentives from ruining products.
