#+title: Books of 2019
#+date: <2020-03-11 17:08>
#+filetags: books

* [[https://www.goodreads.com/book/show/23692271-sapiens][Sapiens]]

#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2020-03/sapiens-cover.jpg

More than any other book this year, /Sapiens/ changed my view of the world. Or at least that's what it felt like while reading. It seemed as if every page contained a new and mind-blowing shift in perspective, such as casting money, democracy, and capitalism as "religions", and questioning the value of civilization in terms of individual human experience. My mind was reeling from the implications of these viewpoints, in a very good way.

On the other hand, my memory of the book is marred by the author's second book, /Homo Deus/, which highlights just how little the author's knowledge of history is worth when extrapolating into the future. It is, essentially, boring and shallow science fiction, with seemingly no knowledge decades of previous writing on the topic.

Come to think about it, this might reveal more about me than the author, for my own expertise is clearly more in science fiction than history; I might simply be much easier to please in the latter than in the former.

* [[https://www.goodreads.com/book/show/785625.The_Boat_Who_Wouldn_t_Float][The Boat Who Wouldn't Float]]

#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2020-03/the-boat-who-wouldnt-float-cover.jpg

This is the partly-fictional account of the author, Mowat Farley, and his boat. That leeks. And stinks. And doesn't sail well. And that is still entirely endearing.

Or maybe it is really about the humor with which the author recounts his misadventures on the Canadian shore. I stuck with this book even though my terrible digital library loaner had whole corrupted pages every chapter or two. But I could neither put it down, nor stop laughing. This might be the funniest book I have read in a decade. I must read more Mowat Farley!

* [[https://www.goodreads.com/series/160439-the-machineries-of-empire][Ninefox Gambit / Raven Stratagem / Revenant Gun]]

#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2020-03/ninefox-gambit-cover.jpg

I did not like the first book in this series. It had a certain spark, but there was so much jargon and confusion, I just couldn't keep up. Yet. I kept coming back to it. That spark.

And in 2019, I bit the bullet, and picked up the sequel. And as with many things in life, it was better the second time around. Even though I still didn't quite get this particular sciency-fantasy-space-opera thing; I now felt at home in it, and could enjoy the story unraveling before me. At which point I couldn't put it down any longer. The /two weeks/ I had to wait after finishing the second book before the third one released were harrowing. A masterpiece!

* [[https://www.goodreads.com/series/191900-the-murderbot-diaries][The Murderbot Diaries]]

#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2020-03/murderbot-cover.jpg

Sometimes I don't want to think. Sometimes I like a simple bit of escapism, like chocolate. Sometimes, I need to read about the Murderbot.

I love how the Murderbot Diaries cast humanity as uncaring and somewhat dim animals, with the most humane characters invariably being artificial intelligences. And the character of Murderbot itself is just so plain delightful, how it simultaneously wants to get away from, yet deeply cares for, us silly, childish humans.

* [[https://www.goodreads.com/book/show/19537969-brains-bullets][Brains vs. Bullets]]

#+ATTR_HTML: :style float:left;margin:5px;margin-right:20px :width 150px
https://bastibe.de/static/2020-03/brains-vs-bullets-cover.jpg

This is an odd one. It's about soldiers, and how they fight. Or rather, what keeps them from fighting. Because every one has a breaking point, and soldiers are often quite close to it when they fight.

And as it turns out, humans are by and large pretty bad at killing each other. Even professional soldiers apparently are often unable to do so, despite years of training and propaganda. Which is a heartening message indeed, for a book on warfare.
