#+title: AI Predictions
#+date: <2024-05-09 10:35>
#+description: My thoughts and predictions about the role of AI in the future. Is it disruptive?
#+filetags: computers

Meta just invested 30 Billion Dollars into AI accelerators[fn:1]. That's roughly equivalent to one Manhattan Project worth of money. Meta must expect a comparable return on that investment. But with that kind of money, that return must be disruptive.

And yet, AI does not /feel/ disruptive. In my life, I have witnessed a few consumer technology disruptions: portable computers, portable telephones, internet-connected "smart" telephones, always-available GPS. Perhaps even tablet computers, smart watches, and electric cars? They all felt exciting! They all felt immediately obviously useful, if perhaps not always to me. But AI does not excite me. So if it's not for me, where is that $30B market that Meta is envisioning?

The best I can think of is a "command line for the common man". But the power of the command line comes from unflinchingly powerful commands, and behaving deterministically. Both of these characteristics are the antithesis of current AI technology. 

We will not give an AI assistant the power to execute "format my hard drive", or "delete my Google account", even though a command line interface clearly would. Yet without that power, the AI assistant is toothless, and less useful. Even if we did, how could we trust the AI assistant to actually do what we want, and not misunderstand us? When interacting with LLMs, I am reminded of Terry Pratchett's gods of the Discworld, who wield absolute power, but you don't want to ask them for help as they're too likely to do what /they think you wanted/ instead of what you actually asked.

But without power, and without deterministic behavior, you can't have a command line experience. 

I keep coming back to that question: What is the /disruptive/ use case of AI? Sure, we'll outsource some tasks to AI that we'd previously outsource overseas. This will result in rampant tragedy, and is already known to be difficult to pull off successfully. We'll enhance many tasks with short snippets of AI, to speed up menial programming tasks, and writing tasks, translation, image generation. But that's a /feature/-addition to existing software, not a disruption, let alone a $30B disruption.

Perhaps I'm wrong. Only time will tell. But I hereby predict that /disruptive/ AI is a bubble.

[fn:1]: For reference, one Billion Dollars is a 1km stack of $100 bills