#+title: The Leica Experience
#+date: <2025-03-16 14:00>
#+description: A review of my experience of the Leica M240 camera
#+filetags: photography

In the world of photography, there is one brand that stands apart from the rest: Leica. It exudes an air of quality, refinement, and heritage. These cameras signal wealth and sophistication, and serve equally as cameras and as fashion pieces. Many of the greatest photographers in history shot their work on Leica. They are very expensive, too. 

That cachet is strongest with their rangefinder series of cameras, which use an anachronistic manual focusing method that relies on optomechanical clockworks instead of digital trickery. Where you frame your shots through a plain window with overlayed framelines, but no digital display or distracting iconography of modern cameras. A reduction to the necessary, pure distilled photography, according to the myth. 

It was thus with much anticipation that I took delivery of a Leica M240 with a Leica 35mm ƒ∕2 “Summicron” lens, loaned graciously by a friend from my local camera club. I have learned enough times to optimize for joy, not utility, so this could be a costly prospect if the experience should appeal to me. 

The camera is indeed a beautiful object, exquisitely machined from solid metals. In an unexpected inversion of modern camera design, it sports a chunky body, but a small lens. A pleasant thing to hold, if a bit more heavy than I had expected. Operation of the camera is indeed pure simplicity. There's a shutter speed dial with an automatic setting, an aperture ring on the lens, and a focus tab. The latter two parameters offer no automation, contrary to modern cameras.

My Leica-using friends in the camera club predicted that I'd get used to the manual focusing quickly. And indeed I did. But precise focusing with a rangefinder is somewhat slow and only possible in the frame center. So where speed is required, I instead relied on good old zone focusing: pre-setting the expected distance on the lens, and stopping down a bit to get a deep zone of focus. Thus prepared to take a shot, there remains nothing but pressing the shutter button. This perfect simplicity of just /being there/, and worrying about nothing but the scene and the composition, feels unexpectedly freeing. On the flip side of course, framing with a window finder is imprecise, and getting accurate focus at large apertures is not easy or fast.

Another surprise were the rangefinder lenses. These are very much unlike modern designs, and focus on compactness and rendering over versatility. They are not sharp wide open, exhibit strong field curvature, and need to be stopped down to get sharp off-center. Annoyingly, the combination of field curvature and the centered rangefinder patch makes anything but center compositions impossible wide open. Still, this is actually a fair tradeoff for smaller lenses, and one I wish more modern lenses would offer, especially as it also tends to make for a smoother focus transition and bokeh. 

Overall, I enjoyed the rangefinder style of shooting. However, the Leica M240 also annoy me a bit by taking too long to switch on. More than once, I raised it to my face, and it simply wasn't ready to shoot yet. It takes a good second to take the next shot, too. Even for a ten year old camera, that is annoyingly slow. I also very much missed a functional, movable back screen, to shoot from low or high angles without contorting myself into camera-yoga, and modern amenities such as USB charging and easy access to the SD card. I'm sure, however, that more modern models are faster at least, even if the back screen does remain fixed and there remains no sensor stabilization.

After two weeks with the camera, I had to return the Leica M240. This is a piece of camera gear I have long wanted to try. I felt the immediacy of the window finder, the simplicity of the rangefinder focusing, the heritage and cachet of the brand. These things were indeed beautiful. But it is still with some relief that I can conclude that this camera is ultimately not for me. I can respect anyone for whom this experience strengthens the connection with the process and images. But for me, I realized that I prefer a camera that goes out of my way, and the Leica is not that.