#+title: Phone Reliability
#+date: <2025-07-26 14:00>
#+description: All our recent phone replacements were due to reliability issues, so I'm buying a Fairphone.
#+filetags: computers

One of our Pixel 6a phones recently had its battery bricked by a [[https://support.google.com/pixelphone/answer/16340779][mandatory software update]]. Conveniently, Google only "found out" about this issue a few months after the warranty period ended for anyone who bought the phone when it was new. Lucky for us, we had bought ours later, when its predecessor broke on vacation and couldn't be repaired. So ours was still covered by its warranty, and we got a full refund.

I noticed that this has been true for all our phone replacements in the last years:
- This Pixel 6a got a mandatory update that bricked its battery, and can't be repaired before we go on vacation. So we now have to buy a new phone.
- A Pixel 5a's screen broke on vacation and local repair shops refused to repair foreign devices. So we had to buy a new phone.
- A Pixel 4a suddenly refused to charge, and I didn't want to wait two weeks to get it repaired. So I bought a new phone.

However, before we used Pixel phones, we had Fairphones, which had quite a different record:
- A screen broke when I dropped it face-first on a radiator. I got a replacement screen fast-shipped within 24h, one day before we left on a trip. The replacement screen with priority shipping cost €98.
- A battery became very weak, and we got a replacement part for €27.
- A charging port became unreliable and we got a replacement part under warranty.
- We replaced a broken headphone socket. The replacement part cost €36.

Needless to say, we will be replacing the Pixel 6a with a Fairphone.