#+title: The Perfect 23mm Lens
#+date: <2025-04-06 14:00>
#+description: A technical comparison of the old and new XF 23mm lenses, as well as the 16-80
#+filetags: photography

What's in a perfect lens? Is it sharpness? Contrast? Microcontrast? Bokeh? Whatever does that even mean?

Today is new lens day. To test my purchase, and get it out of my system, today, I will measure my new lens. It's the Fujifilm XF 23mm f/1.4 R LM WR, a preposterously complex lens for a ridiculously high-resolution camera. Will it prevail against my older Fujifilm XF 23mm f/1.4 R? How will it fare against my travel zoom, the Fujifilm XF 16-80mm f/4 R OIS WR? 

First up, *resolution*: I printed a [[https://www.graphics.cornell.edu/~westin/misc/res-chart.html][test chart]] on A3 paper. First I tried printing the PDF directly with Preview.app, but noticed that the chart itself started blurring lines at 1250 L/PH[fn:1], which implies that Preview.app prints at 1250/8.7in≈150DPI[fn:2]. Not satisfied, I exported the test chart to a high-DPI tiff, and printed with Canon's print application, which appropriately resolved the finest lines on the test chart.

[fn:1] lines per picture height
[fn:2] the height of the measuring area was 8.7in (of the 11.7in paper)

I took pictures of the marked 3:2 area on the chart. Since all my lenses are easily sharp enough to resolve the maximum 20 L/PH on the chart, I aligned the chart to the center quadrant of a 3x3 grid on my camera display, and cropped appropriately in post.

#+begin_export html
<figure style="width: 100%; text-align: center;">
<img width="75%" src="/static/2025-04/Resolution-center.svg" alt="Test shots of a resolution chart in the center of the frame" />
<figcaption>Resolution chart of the image center, with resolution limit as red line in 300x L/PH, and microcontrast in ΔL</figcaption>
</figure>
#+end_export

Each of these crops is at 1:1 resolution of the original capture, *at the center of the frame*, with no sharpening, straight from the raw file. Exposure was adjusted to a consistent 95% L in HSL. The red line indicates the level of resolution where the lines are just resolvable[fn:3]. The resolution scale is in 300x L/PH. For instance, a resolution of 14 corresponds to 4200 L/PH, which is slightly short of the 5150 pixels in the 40 MP image. Since the color filter demosaicing is not entirely lossless, this is an excellent result. 

[fn:3] as judged by my eyes

On average, the new lens resolves a good 10% more lines than the old 23 prime, and perhaps 20% more than the zoom. In the real world, these numbers mean /nothing/. All three of these lenses are easily sharp enough for everything I might throw at them. 

Next to the resolution is the *contrast level* in ΔL[fn:4] (HSL), measured at the right side of this pack of lines, which is a good proxy for contrast of high frequency detail, or microcontrast. A lower black level means more microcontrast. Indeed, this is where the new lens shows a clear improvement over the other two lenses, with visibly more contrast in fine details.

[fn:4] I calibrated the white level to L=95, and ΔL is the difference between the white level and the black level on these lines.

Also notable is a visible magenta *color cast* on the old 23mm prime wide open, and a minor blue color cast on the new 23mm. In normal images, color fringe suppression will mostly get rid of these, so these are not usually worrisome.

And then I repeated the procedure in the *image corners*. I took the same pictures, but this time the resolution chart covered the top-right quadrant of my 3x3 grid:

#+begin_export html
<figure style="width: 100%; text-align: center;">
<img width="75%" src="/static/2025-04/Resolution-corner.svg" alt="Test shots of a resolution chart in the corner of the frame" />
<figcaption>Resolution chart of the image corner, with resolution limit as red line in 300x L/PH, and microcontrast in ΔL</figcaption>
</figure>
#+end_export

As expected, resolution and contrast fall off towards the image corners. For the new lens, the falloff is about 20% resolution, and 40% microcontrast at open apertures, lowering it roughly to the level of the old lens' center. For the old 23mm prime, it's about 40% resolution, and 40% contrast at open apertures, which is visibly soft. The effect diminishes rapidly for smaller apertures, however, and is mostly gone at f/4. Consequently, the 16-80 f/4 merely loses a small bit of contrast.

In *summary* of these objective measurements, the new lens is ridiculously good. In the real world, I would expect to see a minor difference in microcontrast, mostly visible in the image corners. But stop down, and all three lenses will perform very similarly.

As a sanity check, here's the central resolution target, shot a bit closer, to get a feeling for how the above measurements look like on larger structures:

#+begin_export html
<figure style="width: 100%; text-align: center;">
<img width="75%" src="/static/2025-04/Resolution-sanity.svg" alt="Test shots of a low-resolution resolution chart in the center of the frame" />
<figcaption>Resolution target, zoomed out</figcaption>
</figure>
#+end_export

As you can see, the differences in resolution are not a big deal in the real world, and even the contrast levels for larger subjects are not as different as the measurements might suggest. The color fringing wide open is still visible, however.

Next, let's look at the lenses' *bokeh*. For an objective measure, I took a picture of various film boxes along a measuring stick. Focus was at 50cm distance, with the close box at 25cm, and the far one at 75cm. This should give a good indication of the out-of-focus rendering on both sides of the focus plane.

#+begin_export html
<figure style="width: 100%; text-align: center;">
<img width="75%" src="/static/2025-04/Bokeh.svg" alt="Test shots of out-of-focus subjects, to judge bokeh" />
<figcaption>Bokeh evaluation 1: focus is at 50cm, close target at 25 cm, far target at 75 cm</figcaption>
</figure>
#+end_export

You can see a slightly harsher bokeh and very minor color fringes in the old lens at f/1.4. But from these images, I don't see a compelling reason to choose one over the other. Curiously, at f/4, the 16-80 seems to show slightly less blur than the two primes.

For an assessment in more realistic conditions, I took a few photos of flowers and point lights. The flowers give a good indication of the focus transition from in-focus to out-of-focus, while the point lights show how specular highlights are rendered.

#+begin_export html
<figure style="width: 100%; text-align: center;">
<img width="75%" src="/static/2025-04/Bokeh-real.svg" alt="Test shots of real subjects, to judge bokeh" />
<figcaption>Bokeh evaluation 2: focus transition in a bed of flowers, and rendering of point lights</figcaption>
</figure>
#+end_export

The transition pictures once more show a tendency for colored seams on the old prime, which is absent on the new one. This makes the new lens' bokeh seem a little smoother. Apart from that, the differences are very minor. As expected, there is no significant difference in detail between these shots. The point lights essentially confirm this, with a bit more color fringing on the old lens.

In *conclusion*, I found the new Fujifilm XF 23mm R LM WR slightly sharper than the old Fujifilm XF 23mm R, with noticeably less color fringing, and slightly better microcontrast. Once stopped down to f/4, these differences become insignificant. At that point, both prime lenses retain a very minor resolution advantage over the Fujifilm XF 16-80 R OIS WR.

Thus my curiosity in the technical quality of these lenses is satisfied, I verified that my lens is functioning properly, and I can now go out and shoot pictures.